export const GET_FEED: "GET_FEED" = "GET_FEED";
export const GET_FEED_SUCCESS: "GET_FEED_SUCCESS" = "GET_FEED_SUCCESS";
export const GET_FEED_FAILED: "GET_FEED_FAILED" = "GET_FEED_FAILED";

export const GET_ORDER: "GET_ORDER" = "GET_ORDER";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";

export const AUTH: "AUTH" = "AUTH";
export const AUTH_SUCCESS: "AUTH_SUCCESS" = "AUTH_SUCCESS";
export const AUTH_FAILED: "AUTH_FAILED" = "AUTH_FAILED";

export const GET_FILLING: "GET_FILLING" = "GET_FILLING";

export const GET_CURRENT_CARD: "GET_CURRENT_CARD" = "GET_CURRENT_CARD";
export const REMOVE_CURRENT_CARD: "REMOVE_CURRENT_CARD" = "REMOVE_CURRENT_CARD";

export const UPDATE_FILL: "UPDATE_FILL" = "UPDATE_FILL";
export const UPDATE_BUN: "UPDATE_BUN" = "UPDATE_BUN";
export const DELETE_FILL: "DELETE_FILL" = "DELETE_FILL";
export const SORTING: "SORTING" = "SORTING";

export const GET_USER: "GET_USER" = "GET_USER";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";
export const DELETE_USER: "DELETE_USER" = "DELETE_USER";
export const LOGOUT_FAILED: "LOGOUT_FAILED" = "LOGOUT_FAILED";

export const OPEN_POPUP_ORDER_PAGE: "OPEN_POPUP_ORDER_PAGE" =
  "OPEN_POPUP_ORDER_PAGE";
export const OPEN_POPUP_INGR_PAGE: "OPEN_POPUP_INGR_PAGE" =
  "OPEN_POPUP_INGR_PAGE";

export const SET_INGR_POPUP: "SET_INGR_POPUP" = "SET_INGR_POPUP";
export const SET_ORDER_POPUP: "SET_ORDER_POPUP" = "SET_ORDER_POPUP";
export const SET_ORDER_INFO_POPUP: "SET_ORDER_INFO_POPUP" =
  "SET_ORDER_INFO_POPUP";

export const OPEN_POPUP: "OPEN_POPUP" = "OPEN_POPUP";
export const CLOSE_POPUP: "CLOSE_POPUP" = "CLOSE_POPUP";

export const POST_EMAIL: "POST_EMAIL" = "POST_EMAIL";
export const POST_EMAIL_SUCCESS: "POST_EMAIL_SUCCESS" = "POST_EMAIL_SUCCESS";
export const POST_EMAIL_FAILED: "POST_EMAIL_FAILED" = "POST_EMAIL_FAILED";

export const REGISTER: "REGISTER" = "REGISTER";
export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = "REGISTER_SUCCESS";
export const REGISTER_FAILED: "REGISTER_FAILED" = "REGISTER_FAILED";

export const POST_PASSWORD: "POST_PASSWORD" = "POST_PASSWORD";
export const POST_PASSWORD_SUCCESS: "POST_PASSWORD_SUCCESS" =
  "POST_PASSWORD_SUCCESS";
export const POST_PASSWORD_FAILED: "POST_PASSWORD_FAILED" =
  "POST_PASSWORD_FAILED";

export const UPDATE_TOKEN: "UPDATE-TOKEN" = "UPDATE-TOKEN";
export const UPDATE_TOKEN_SUCCESS: "UPDATE-TOKEN_SUCCESS" =
  "UPDATE-TOKEN_SUCCESS";
export const UPDATE_TOKEN_FAILED: "UPDATE-TOKEN_FAILED" = "UPDATE-TOKEN_FAILED";

export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =
  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" =
  "WS_CONNECTION_CLOSED";
export const WS_CONNECTION_CLOSE: "WS_CONNECTION_CLOSE" = "WS_CONNECTION_CLOSE";
export const WS_GET_MESSAGE: "WS_GET_MESSAGE" = "WS_GET_MESSAGE";

export const USER_WS_CONNECTION_SUCCESS: "USER_WS_CONNECTION_SUCCESS" =
  "USER_WS_CONNECTION_SUCCESS";
export const USER_WS_CONNECTION_ERROR: "USER_WS_CONNECTION_ERROR" =
  "USER_WS_CONNECTION_ERROR";
export const USER_WS_CONNECTION_CLOSED: "USER_WS_CONNECTION_CLOSED" =
  "USER_WS_CONNECTION_CLOSED";
export const USER_WS_CONNECTION_CLOSE: "USER_WS_CONNECTION_CLOSE" =
  "USER_WS_CONNECTION_CLOSE";
export const USER_WS_GET_MESSAGE: "USER_WS_GET_MESSAGE" = "USER_WS_GET_MESSAGE";
export const USER_WS_SEND_MESSAGE: "USER_WS_SEND_MESSAGE" =
  "USER_WS_SEND_MESSAGE";

export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const USER_WS_CONNECTION_START: "USER_WS_CONNECTION_START" =
  "USER_WS_CONNECTION_START";
