export const GET_FEED = 'GET_FEED'
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS'
export const GET_FEED_FAILED = 'GET_FEED_FAILED'

export const GET_ORDER = 'GET_ORDER'
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'

export const
    AUTH = 'AUTH',
    AUTH_SUCCESS = 'AUTH_SUCCESS',
    AUTH_FAILED = 'AUTH_FAILED',

    GET_FILLING = 'GET_FILLING',
    GET_CURRENT_CARD = 'GET_CURRENT_CARD',
    REMOVE_CURRENT_CARD = 'REMOVE_CURRENT_CARD',

    UPDATE_FILL = 'UPDATE_FILL',
    UPDATE_BUN = 'UPDATE_BUN',
    DELETE_FILL = 'DELETE_FILL',
    SORTING = 'SORTING',

    GET_USER = "GET_USER",
    GET_USER_SUCCESS = "GET_USER_SUCCESS",
    GET_USER_FAILED = 'GET_USER_FAILED',
    DELETE_USER = 'DELETE_USER',

    OPEN_POPUP_ORDER_PAGE = 'OPEN_POPUP_ORDER_PAGE',
    OPEN_POPUP_INGR_PAGE = 'OPEN_POPUP_INGR_PAGE',

    SET_INGR_POPUP = 'SET_INGR_POPUP',
    SET_ORDER_POPUP = "SET_ORDER_POPUP",
    SET_ORDER_INFO_POPUP = 'SET_ORDER_INFO_POPUP',

    OPEN_POPUP = 'OPEN_POPUP',
    CLOSE_POPUP = 'CLOSE_POPUP',

    POST_EMAIL = 'POST_EMAIL',
    POST_EMAIL_SUCCESS = 'POST_EMAIL_SUCCESS',
    POST_EMAIL_FAILED = 'POST_EMAIL_FAILED',

    REGISTER = 'REGISTER',
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAILED = 'REGISTER_FAILED',

    POST_PASSWORD = 'POST_PASSWORD',
    POST_PASSWORD_SUCCESS = 'POST_PASSWORD_SUCCESS',
    POST_PASSWORD_FAILED = 'POST_PASSWORD_FAILED',

    UPDATE_TOKEN = 'UPDATE_TOKEN',
    UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS',
    UPDATE_TOKEN_FAILED = 'UPDATE_TOKEN_FAILED',

    WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS',
    WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR',
    WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED',
    WS_CONNECTION_CLOSE = 'WS_CONNECTION_CLOSE',
    WS_GET_MESSAGE = 'WS_GET_MESSAGE',

    USER_WS_CONNECTION_SUCCESS = 'USER_WS_CONNECTION_SUCCESS',
    USER_WS_CONNECTION_ERROR = 'USER_WS_CONNECTION_ERROR',
    USER_WS_CONNECTION_CLOSED = 'USER_WS_CONNECTION_CLOSED',
    USER_WS_CONNECTION_CLOSE = 'USER_WS_CONNECTION_CLOSE',
    USER_WS_GET_MESSAGE = 'USER_WS_GET_MESSAGE'


